version: '3'
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
  web:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./backend/:/backend/
    depends_on:
      - db
