version: '3'
services:
  web:
    container_name: backend
    image: chltpdus48/github-actions-session
    build: .
    ports:
      - "8000:8000"
    command:
      - sh
      - -c
      - |
        python manage.py makemigrations
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000


#--settings=config.settings.prod