version: '3'
services:
  web:
    container_name: backend
    image: chltpdus48/github-actions-session
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_NAME: $DATABASE_NAME
        DATABASE_USER: $DATABASE_USER
        DATABASE_PASSWORD: $DATABASE_PASSWORD
        DATABASE_HOST: $DATABASE_HOST
        DATABASE_PORT: $DATABASE_PORT
        SECRET_KEY: $SECRET_KEY
    ports:
      - "8000:8000"
    command:
      - sh
      - -c
      - |
        python manage.py migrate --settings=config.settings.prod
        python manage.py runserver 0.0.0.0:8000 --settings=config.settings.prod